### ISSUE TITLE
xmldom is not active anymore.

### ISSUE THREAD

**Issue by natlibfi-jonollil** [NatLibFi/marc-record-serializers#20]
https://www.npmjs.com/package/xmldom no updates in 3 years.

Possible replacement https://www.npmjs.com/package/fast-xml-parser ?

**Comment by natlibfi-arlehiko** [comment]
Good catch! I'd go with [https://www.npmjs.com/package/xml2js](xml2js) since we're already using it elsewhere and it makes manipulating XML-like structure more enjoyable.

However, if `fast-xml-parser` is a drop-in replacement for `xmldom` we could go with that too.

So:

- Prefer `xml2js` to `fast-xml-parser` if the code needs to be rewritten anyway
- Either way, the new module must support **both** Node.js and browsers.

**Comment by natlibfi-arlehiko** [comment]
`xmldom` seems to be active again.
